### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ospfrip** [mtarek/compitex#5]
==output
Core was generated by `./compitex my.txt'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000004068b8 in ex (p=0x17855d0) at codegen.c:269
269             Parameter *par = (Parameter *)it->data;

==
   because it->size == 0,  
  [root@localhost compitex]# cat my.txt 
\frac{1}{2};
==
   can you give a example for my.txt ?

**Comment by ospfrip** [comment]
have solved bug:
   codegen.c   modify ：
  263 int ex(nodeType *p) {
    264     char mainbuf[MAXEXP];
    265     int i = 0;
    266     memset(mainbuf, 0, MAXEXP);
    267 
    268         List ple;
    269         List *parlist = &ple;
    270         List_init(parlist, Parameter_eq);
    271 
    272     _parampass(parlist, p);
    273  
    274      if (parlist->size == 0){      //add math exprosession example:  1+2;
    275             goto my;                  //add 
    276      }

   316 my:        // if size is zero, go to here
    317 
    318     _sumpass(mainbuf, p, 1);
    319     fprintf(_out, "%s\n", mainbuf);
    320 
    321     memset(mainbuf, 0, MAXEXP);
    322 
    323     _ex2(mainbuf, p);
    324     fprintf(_out, "%s;\n\n", mainbuf);
    325     return 0;
    326 }

**Comment by erentar** [comment]
I also have this problem
